[package]
name = "ax1600i"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3"
libusb = "0.3"
crc = "^1.0.0"
